networks:
  puntonet_network:
    driver: bridge

volumes:
  pgdata:
  redis_data:
  alembic_migrations:

services:
  pn-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pn-db
      - pn-redis
    image: puntonetbackend:latest
    container_name: pn-template
    env_file:
      - ./.env
    ports:
      - "8010:8000"
    volumes:
      - ./secrets:/develop/secrets:ro
      - ./media:/develop/media:rw
      - alembic_migrations:/develop/alembic/versions
    networks:
      - puntonet_network

  pn-db:
    image: postgres:16
    container_name: pn-postgres_db
    restart: always
    env_file:
      - ./.env
    expose:
      - 5432
    networks:
      - puntonet_network
    volumes:
      - pgdata:/var/lib/postgresql/data

  pn-redis:
    image: redis:7-alpine
    container_name: pn-redis
    expose:
      - 6379
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - puntonet_network